"""adiciona media a blog_posts

Revision ID: 24efa0cbf722
Revises: 9ddef631a266
Create Date: 2026-09-30 21:40:14.643873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24efa0cbf722'
down_revision: Union[str, Sequence[str], None] = '9ddef631a266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('media', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_posts', 'media')
    # ### end Alembic commands ###
